name: Build PintelNet APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Build APK
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-17-jdk zip
        pip3 install buildozer cython==0.29.33
        buildozer -v android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: pintelnet-apk
        path: bin/*.apk
        retention-days: 30
