name: Build PintelNet APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-17-jdk \
          zip \
          unzip
          
    - name: Install Buildozer and dependencies
      run: |
        pip3 install --user buildozer
        pip3 install --user cython==0.29.33
        
    - name: Build APK with Buildozer (auto-download SDK)
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        # Forzar descarga limpia del SDK
        rm -rf ~/.buildozer/android/platform/android-sdk
        buildozer -v android debug
        ls -la bin/
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: pintelnet-apk
        path: bin/*.apk
        retention-days: 30
