name: Build PintelNet APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install ALL system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-venv \
          autoconf \
          automake \
          build-essential \
          ccache \
          cmake \
          cython3 \
          gettext \
          libffi-dev \
          libltdl-dev \
          libssl-dev \
          libtool \
          openjdk-11-jdk \
          pkg-config \
          python3-dev \
          zlib1g-dev \
          git \
          wget \
          curl \
          unzip
          
    - name: Install Python dependencies
      run: |
        pip3 install --user cython==0.29.33
        pip3 install --user buildozer
        
    - name: Build APK with Buildozer
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        buildozer android debug
        ls -la bin/
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: pintelnet-apk
        path: bin/*.apk
        retention-days: 30
